spring:
  redis:
    host: r-wz95887bf628b004pd.redis.rds.aliyuncs.com
    port: 6379
    password: Lyd13422356022    # 密码（默认为空）
    database: 1
    timeout: 15000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
    ws-topic-name: project_websocket #websocket推送redis主题的名称
#  rabbitmq:
#    host: 106.12.114.13
#    port: 5672
#    username: admin
#    password: admin
#    listener:
#      simple:
#        acknowledge-mode: manual

# websocket监听端口，默认8088
netty:
  websocket:
    #是否开启服务
    enabled: true
    #监听端口
    port: 9588