spring:
  redis:
    host: r-wz9mvlqkzmhhkz4vvo.redis.rds.aliyuncs.com
    port: 6379
    password: Hgls2019%&       # 密码（默认为空）
    database: 15
    timeout: 6000ms  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
    ws-topic-name: school_websocket #websocket推送redis主题的名称
  rabbitmq:
    host: 112.74.186.198
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual

# websocket监听端口，默认8088
netty:
  websocket:
    #是否开启服务
    enabled: true
    #监听端口
    port: 9588